version: "3"
  
services:
  solana:
    container_name: solana
    image: neonlabsorg/solana:v1.9.12-testnet-with_trx_cap
    environment:
      SOLANA_URL: http://solana:8899
      RUST_LOG: solana_runtime::system_instruction_processor=trace,solana_runtime::message_processor=debug,solana_bpf_loader=debug,solana_rbpf=debug
    hostname: solana
    ports:
      - 127.0.0.1:8899:8899
      - 127.0.0.1:8900:8900
      - 127.0.0.1:8001-8009:8001-8009/udp
    expose:
      - "8899"
      - "9900"
      - "8900"
      - "8001"
      - "8001-8009/udp"
    networks:
      - net
    healthcheck:
      # Must be available from outside (calling without -u causes premature result)
      test: [ CMD-SHELL, "solana cluster-version -u http://solana:8899" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  evm_loader:
    container_name: evm_loader
    image: neonlabsorg/evm_loader:test
    environment:
      - SOLANA_URL=http://solana:8899
    networks:
      - net
    depends_on:
      solana:
        condition: service_healthy
    command: bash -c "create-test-accounts.sh 1 && deploy-evm.sh"

networks:
  net:
